
//This file was generated by the BlueberryPI Admin page

//If you are hosting the front end interface on a different

//machine you will have to edit this file directly

var apiKey='b33140f68263dd01525a5bd934d64bbb';
