
//This file was generated by the BlueberryPI Admin page

//If you are hosting the front end interface on a different

//machine you will have to edit this file directly

var apiKey='e6f08cd2a2d7c4521328bdd193fd479a';
